name = "studio-website"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-10-10"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
# Control Plane base URL for web runtime
PUBLIC_RKS_WORKER_URL = "https://studio-control-plane.rawkodeacademy.workers.dev"
