name = "studio-website"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-10-10"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

